//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.27 at 02:11:01 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://services.web.soap.springboot.rymasheuski.epam.com/contacts", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.epam.rymasheuski.springboot.soap.web.services.contacts;
